# Programación para la Bioinformática

Módulo 4: Librerías científicas en Python - NumPy - Ejercicios
-------------------------------------------------

Ejercicios y preguntas teóricas
-------------------------------

### Ejercicio 1
Cread una matriz de 8x8 que tenga un patrón 0 (blancas)/1 (negras) como si se tratara de un tablero de ajedrez. El resultado ha de ser:

```
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]
```

In [10]:
# Respuesta
import numpy as np

matriz_zero = np.zeros((8,8), dtype=int) #Create list of 0 as int
print(matriz_zero.shape) #Et diu com es la matriu
matriz_zero[1::2,::2] = 1 #Antes de la coma decido las filas, despues de la coma decido que sea 0,1,0,1
matriz_zero[::2,1::2] = 1
#array = ndarray
print(matriz_zero)

(8, 8)
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Ejercicio 2
Cread dos matrices de tamaño 6x4 y 4x4 con números reales aleatorios y obtened la matriz resultado de multiplicar la primera por la segunda:

In [13]:
# Respuesta
random_six_four = np.random.randint(10, size=(6,4))
random_four_four = np.random.randint(10, size=(4,4))

print(random_six_four.dot(random_four_four))

[[ 75 139 125  96]
 [ 86  96 108  80]
 [100 108 101  90]
 [ 65  64  80  57]
 [ 92  96 111  80]
 [ 88 146 103 104]]


### Ejercicio 3
Calculad la media y la desviación estándar de un vector aleatorio de 300 elementos:

In [215]:
# Respuesta
SIZE = 300
vector = np.random.randint(0, 10, SIZE)

average = np.average(vector)

standard_desviation = np.std(vector)

print("Average: %3.2f" %average)
print("Standard desviation: %3.2f" %standard_desviation)

Average: 4.69
Standard desviation: 2.85


### Ejercicio 4
Evaluad las funciones seno y arcoseno en el intervalo [-1,1] y con paso (resolución) de 0.025 y guardadlas en dos arrays (evaluar significa calcular):

In [17]:
# Respuesta
intervalo = np.arange(-1, 1, 0.025)
print(intervalo)
function_sin = np.sin(intervalo)
function_arcsin = np.arcsin(intervalo)


print("Function sin: ")
print(function_sin)
print("")
print("Function arcsin: ")
print(function_arcsin)



[-1.0000000e+00 -9.7500000e-01 -9.5000000e-01 -9.2500000e-01
 -9.0000000e-01 -8.7500000e-01 -8.5000000e-01 -8.2500000e-01
 -8.0000000e-01 -7.7500000e-01 -7.5000000e-01 -7.2500000e-01
 -7.0000000e-01 -6.7500000e-01 -6.5000000e-01 -6.2500000e-01
 -6.0000000e-01 -5.7500000e-01 -5.5000000e-01 -5.2500000e-01
 -5.0000000e-01 -4.7500000e-01 -4.5000000e-01 -4.2500000e-01
 -4.0000000e-01 -3.7500000e-01 -3.5000000e-01 -3.2500000e-01
 -3.0000000e-01 -2.7500000e-01 -2.5000000e-01 -2.2500000e-01
 -2.0000000e-01 -1.7500000e-01 -1.5000000e-01 -1.2500000e-01
 -1.0000000e-01 -7.5000000e-02 -5.0000000e-02 -2.5000000e-02
  8.8817842e-16  2.5000000e-02  5.0000000e-02  7.5000000e-02
  1.0000000e-01  1.2500000e-01  1.5000000e-01  1.7500000e-01
  2.0000000e-01  2.2500000e-01  2.5000000e-01  2.7500000e-01
  3.0000000e-01  3.2500000e-01  3.5000000e-01  3.7500000e-01
  4.0000000e-01  4.2500000e-01  4.5000000e-01  4.7500000e-01
  5.0000000e-01  5.2500000e-01  5.5000000e-01  5.7500000e-01
  6.0000000e-01  6.25000

### Ejercicio 5
En química computacional, es muy útil simular mediante la técnica de dinámica molecular cómo pequeños ligandos (por ejemplo, la aspirina) se unen a otras proteínas. Esta unión entre una proteína y un ligando puede bloquear la unión de esa misma proteína junto a otras, potenciarla, etc.
En nuestro caso, hemos obtenido dos capturas del movimiento de la molécula de aspirina y deseamos saber cuál es la distancia en términos de RMSD entre ambas, es decir, cuánto se ha movido entre una captura y la otra. Si representáramos ese movimiento, podríamos visualizar algo similar a esto:

<img src="files/media/aspirin_structures.png">

A continuación, tenéis parte del código que deberéis completar para calcular la distancia RMSD que está definida de la siguiente forma: https://en.wikipedia.org/wiki/Root-mean-square_deviation_of_atomic_positions.  

<img src="files/media/rmsd.svg">

La variable *estructura_1* contiene la información de las coordenadas de los átomos de la primera captura y *estructura_2* la segunda:

In [22]:
import numpy as np
import os


# Estructura atómica en formato PDB
estructura_1 = """
HETATM    1  C4  AIN A 141      20.988  20.013   8.918  1.00 32.08           C
HETATM    2  C3  AIN A 141      19.732  19.385   8.857  1.00 32.34           C
HETATM    3  C2  AIN A 141      19.527  18.104   9.636  1.00 33.22           C
HETATM    4  C5  AIN A 141      21.977  19.496   9.752  1.00 31.39           C
HETATM    5  H4  AIN A 141      21.183  20.890   8.320  1.00  0.00           H
HETATM    6  C6  AIN A 141      21.761  18.347  10.492  1.00 31.52           C
HETATM    7  H5  AIN A 141      22.932  19.991   9.830  1.00  0.00           H
HETATM    8  C1  AIN A 141      20.570  17.658  10.434  1.00 32.96           C
HETATM    9  H6  AIN A 141      22.537  17.967  11.139  1.00  0.00           H
HETATM   10  H1  AIN A 141      20.440  16.756  11.015  1.00  0.00           H
HETATM   11  C7  AIN A 141      18.679  19.893   7.921  1.00 32.12           C
HETATM   12  O1  AIN A 141      18.856  21.012   7.231  1.00 28.52           O
HETATM   13  O2  AIN A 141      17.582  19.373   7.818  1.00 32.90           O
HETATM   14  O3  AIN A 141      18.290  17.505   9.519  1.00 35.01           O
HETATM   15  C8  AIN A 141      17.117  17.595  10.410  1.00 35.75           C
HETATM   16  O4  AIN A 141      16.308  16.678  10.381  1.00 37.46           O
HETATM   17  C9  AIN A 141      16.879  18.753  11.344  1.00 36.44           C
HETATM   18  H91 AIN A 141      15.952  18.591  11.895  1.00  0.00           H
HETATM   19  H92 AIN A 141      17.709  18.830  12.046  1.00  0.00           H
HETATM   20  H93 AIN A 141      16.803  19.676  10.769  1.00  0.00           H
"""

estructura_2 = """
HETATM    1  C4  AIN A 141      20.909  19.934   8.896  1.00 32.08           C
HETATM    2  C3  AIN A 141      19.652  19.312   8.766  1.00 32.34           C
HETATM    3  C2  AIN A 141      19.387  18.158   9.565  1.00 33.22           C
HETATM    4  C5  AIN A 141      21.860  19.487   9.821  1.00 31.39           C
HETATM    5  H4  AIN A 141      21.131  20.820   8.331  1.00  0.00           H
HETATM    6  C6  AIN A 141      21.586  18.379  10.634  1.00 31.52           C
HETATM    7  H5  AIN A 141      22.771  20.048   9.926  1.00  0.00           H
HETATM    8  C1  AIN A 141      20.364  17.703  10.480  1.00 32.96           C
HETATM    9  H6  AIN A 141      22.314  18.043  11.358  1.00  0.00           H
HETATM   10  H1  AIN A 141      20.171  16.825  11.079  1.00  0.00           H
HETATM   11  C7  AIN A 141      18.638  19.970   7.867  1.00 32.12           C
HETATM   12  O1  AIN A 141      18.979  20.954   7.165  1.00 28.52           O
HETATM   13  O2  AIN A 141      17.431  19.667   7.937  1.00 32.90           O
HETATM   14  O3  AIN A 141      18.249  17.398   9.458  1.00 35.01           O
HETATM   15  C8  AIN A 141      17.235  17.488  10.335  1.00 35.75           C
HETATM   16  O4  AIN A 141      16.343  16.644  10.397  1.00 37.46           O
HETATM   17  C9  AIN A 141      17.211  18.698  11.261  1.00 36.44           C
HETATM   18  H91 AIN A 141      16.416  18.581  11.994  1.00  0.00           H
HETATM   19  H92 AIN A 141      18.154  18.814  11.795  1.00  0.00           H
HETATM   20  H93 AIN A 141      17.020  19.587  10.663  1.00  0.00           H
"""

def lee_coordenadas_atomo(linea):
    """Obtiene de una línea de texto en formato PDB las coordenadas en f
    ormato numérico"""
    if linea.startswith('HETATM'):
        x = float(linea[30:38])    # Coordenada x
        y = float(linea[38:46])    # Coordenada y
        z = float(linea[46:54])    # Coordenada z
        return [x, y, z]

    
def obtiene_coordenadas(estructura):
    """Transforma las coordenadas de cada átomo en un array numpy"""
    coordenadas = []
    for linea in estructura.split(os.linesep):
        atomo = lee_coordenadas_atomo(linea)
        if atomo:
            coordenadas.append(atomo)
    return np.array(coordenadas)


def calcula_rmsd_numpy(coordenadas_1, coordenadas_2):
    """Calcula la RMSD entre dos conjuntos de coordenadas atómicas"""
    # Aquí es dónde tenéis que completar el código. La solución puede ser 
    # una sola línea gracias a la capacidad de NumPy de hacer cálculos con 
    # matrices mediante "broadcast".
    # Si no dais con una solución en una línea no hay problema :)
    
    rmsd = 0.0 # Esta es la línea a modificar con vuestra solución
    rmsd = np.sqrt(np.sum((coordenadas_2-coordenadas_1)**2)/len(coordenadas_1))

coordenadas_1 = obtiene_coordenadas(estructura_1)
coordenadas_2 = obtiene_coordenadas(estructura_2)

rmsd = calcula_rmsd_numpy(coordenadas_1, coordenadas_2)

print(rmsd)

None


**El resultado del cálculo de la RMSD ha de ser de `0.253808096798`, no puede ser un número entero.**

### Ejercicio 6

Crea un vector de números enteros aleatorios de 30 posiciones y ordénalo:

In [237]:
# Respuesta
vector = np.random.randint(10, size=30)
print(np.sort(vector))

[0 0 0 0 1 1 2 2 2 3 3 3 4 4 4 4 4 4 5 5 5 5 5 6 6 6 7 9 9 9]


### Ejercicio 7

Dado un vector `Z` con números aleatorios entre 0 y 1 de 100 posiciones y un valor `v` aleatorio entre 0 y 1, encuentra cuál es el valor en `Z` más próximo a `v`:

In [ ]:
import numpy as np

vector = np.random.random(100)
valor = np.random.uniform(0,1)
print(vector)
# Respuesta
idx = (np.abs(vector - valor)).argmin() #Estoy restando el valor al vector, le doy valor absoluto para que no tenga
                                        #numeros negativos y solo tenga la diferencia entre cada valor del vector y el valor unico.
                                        #una vez tengo esto, busco el menor valor obtenido.
print(idx)
print(np.abs(vector - valor))
print(vector[idx])


### Ejercicio 8

En un vector de 100 posiciones, encuentra cuál es el valor que se repite de forma más frecuente:

In [29]:
import numpy as np

Z = np.random.randint(0,10,100)

print(Z)

# Respuesta
counts = np.bincount(Z)  #Order in array and count the numbers
ind2 = np.argmax(counts) #The bigger. If there is more than 1 number don't appear
print(ind2)

[8 2 3 7 5 9 2 4 6 7 1 5 4 5 5 0 9 6 8 3 8 2 1 8 5 9 7 9 9 9 8 2 3 9 3 7 7
 3 0 8 1 0 4 7 1 5 4 3 6 6 3 8 4 9 8 7 0 1 8 6 2 5 2 3 1 0 2 9 2 2 2 9 4 2
 5 7 8 7 1 9 0 6 1 1 6 5 7 0 6 3 8 3 7 6 9 3 5 4 1 2]
[ 7 10 12 11  7 10  9 11 11 12]
2
